apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240110035809.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240110035809.0.0+build.02e9424
  releaseNotes: |
    Release v20240110035809.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-01-2024-22-03-28-223113162/where-for-dinner-my-apps-bundle@sha256:7416c48feb6c560b93b8b3280eb51e856110677003a5a0257b1c242fcf617c9b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

